### PR TITLE
Completed Tasks

### PR DESCRIPTION
**Pull request by Milanoboy20**
ShopProductServiceImpl
ShopProductRepository
ShopProductService
ShopProductIntegrationTest

### CODE REVIEW

**Review by iatenine — CHANGES_REQUESTED** [review]
Awaiting integration of config/models

**Comment by Milanoboy20** [comment]
Made the model integration, should work now.

**Review by RichardSimpson235 — COMMENTED** [review]
In ShopProductServiceImpl it makes more sense to return the Optional doesn't it? The controller layer can just call isPresent to know if it got a valid ShopProduct or not, and ResponseEntity has methods for using Optionals for returning the correct status codes and response bodies.

In ShopProductIntegrationTest it would be better if you asserted that the size of the list is what you expected based on the data.sql file.

For the getDiscoutedShopProducts test, I'm a bit confused why this test is here. The logic for getting discounted items seems like it'd belong in a service layer class that would get tested by this method.

**Comment by Milanoboy20** [comment]
lol i forgot to delete the discount test, nvm that one
ShopProductServiceImpl getShopProductById(int id) method already returns an Optional, or you mean just make it return shopProduct without the isPresent() / ternary operation check?

**Review by RichardSimpson235 — COMMENTED** [review]
The check is fine if you can't think of any extra logic that that mehtod might have. but it should return Optional.empty() not Optional.of(new ShopProduct()). Optional.of(new ShopProduct()) would have isPresent return true, and the controller would end up returning an empty object to the client.

**Review by RichardSimpson235 — COMMENTED** [review]
Did you try running your tests? When I do the smoke test fails saying the data.sql file has an error. I'm guessing it might be because strings need to be single quotes.

**Comment by Milanoboy20** [comment]
Yes they do, and if you're wondering, I did not include my data.sql int this repo.
I can add it if you want it for the tests

**Comment by RichardSimpson235** [comment]
Ah ok, can you include the sql file so I can confirm it works?

**Comment by Milanoboy20** [comment]
added it now

**Comment by redn6gx** [comment]
All tests pass with mock classes

**Pull request merged**
