### PR TITLE
Feature product display tommy

### PR DESCRIPTION
**Pull request by tanbessaw**

### CODE REVIEW

**Review by RichardSimpson235 — CHANGES_REQUESTED** [review]
I would hope the ProductService returns Optionals so you don't have to do null checking like this. (ProductController line 22)

In ProductControllerTests refactor the success and fail cases of your unit test into two different methods (so something like testGetProductByIdSuccess and testGetProductByIdFailure). It'll be easier to debug or confirm the application is working in the long run if we can see it that way.

To answer your question online 21 of ProductServiceIntegrationTest, h2 is fine. We can do postgres in the e2e testing. In an enterprise environment like Walmart we might try it with the actual database simply because the infrastructure is more complicated, but here it should be fine.

**Review by RichardSimpson235 — CHANGES_REQUESTED** [review]
In ShopProductController let's be using Optionals instead of doing null checks ourselves (line 23 and 25). You should check ResponseEntity's documentation, you can make this better by using ResponseEntity.of(). Turns this whole method into one line of code: ReponseEntity.of(sps.getShopProductByShopId(...)). Check ReponseEntity.of's documentation if it isn't clear what this does (and obviously fill in the ...).

**Comment by RichardSimpson235** [comment]
You don't have to use ResponseEntity's static methods, but I would like it if we all used Optionals

**Comment by redn6gx** [comment]
Everything looks good

**Pull request merged**
